name: Build FFmpegKit Android AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3 openjdk-17-jdk

      - name: Build ffmpeg-kit (MIT full)
        run: |
          cd android
          chmod +x android.sh
          ./android.sh --lts --full

      - name: List AAR files
        run: ls -lh android/build/outputs/aar/

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-aar
          path: android/build/outputs/aar/*.aar
